# Generated by Django 4.1.3 on 2022-11-19 11:05

import book_shop.models.book
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Название книги')),
                ('count', models.BigIntegerField(default=0, validators=[book_shop.models.book.greater_than_zero], verbose_name='Количество на складе')),
                ('price', models.BigIntegerField(validators=[book_shop.models.book.greater_than_zero], verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='authors', to='book_shop.author', verbose_name='Имя автора')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='book_shop.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Автор книги',
                'verbose_name_plural': 'Авторы книги',
                'unique_together': {('author', 'book')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='book_authors', through='book_shop.BookAuthor', to='book_shop.author'),
        ),
    ]
