# Generated by Django 4.1.3 on 2022-11-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0002_book_bookauthor_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=1024, verbose_name='Заказчик')),
                ('books', models.ManyToManyField(related_name='ordered_books', to='book_shop.book')),
            ],
        ),
    ]
